Fixing NullPointerException when autocompleting parameters for a function without any parameters (#249)
```
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "pl.thedeem.intellij.dql.services.definition.model.Signature.parameters()" is null
	at pl.thedeem.intellij.dql.completion.engines.DQLFunctionParametersCompletion.autocomplete(DQLFunctionParametersCompletion.java:36)
	at pl.thedeem.intellij.dql.completion.DQLLocalCompletionContributor$2.addCompletions(DQLLocalCompletionContributor.java:21)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:23)
```